-- return {
--   'LowByteFox/bun.nvim',
--   dependencies = {
--     'nvim-treesitter/nvim-treesitter',
--     'akinsho/toggleterm.nvim'
--   },
--   config = function()
--     require('bun').setup({
--       close_on_exit = true | false, -- if the terminal window should close instantly after bun exited
--       cwd = "current" | "relative", -- run_current's working directory
--       -- if "current" it will use current working directory of NeoVim
--       -- if "relative" it will use directory where the file is located
--       direction = "horizontal" | "float" -- float will create floating window and horizontal will put it under buffers
--     })
--   end
-- }
